heat_template_version: 2013-05-23

description: |
  Deploys a Provider LBer for VLAN backed Provider networks.
parameters:

  external_network_id:
    type: string
    label: ext-net
    description: UUID of a Neutron external network
    default: fdb92e61-75e4-47ef-9b74-557af5b6147e

  provider_network_id:
    type: string
    label: provider-net
    description: UUID of a Neutron external network
    default: db10e40b-444e-4297-80c6-6d62b4779ca7

  provider_subnet_id:
    type: string
    label: provider-subnet
    description: UUID of a Neutron external network
    default: 41d5eeb1-7336-4c61-b840-7407281e21e1

resources:

  lb_01:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      name: Provider-NN-LB-01
      value_specs: {router_type: exclusive}
      external_gateway_info: { "network": { get_param: external_network_id }}
  lb_int0:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: lb_01 }
      port: { get_resource: lb_port0 }
  lb_port0:
    type: OS::Neutron::Port
    properties:
       admin_state_up: true
       network_id: { get_param: provider_network_id }
       fixed_ips:
          - subnet: { get_param: provider_subnet_id }
